---
version: '3'
services:
  dev-maven:
    build: dev/
    container_name: dev-maven
    volumes:
    #  - app42-content:/usr/share/app-src/target
      - app42-config:/usr/share/app-conf
      - app42-webdata:/usr/share/app-src/WebContent 

  prod-tomcat:
     image: tomcat:9.0-jre8-alpine
     container_name: prod-tomcat
     depends_on:
       - dev-maven
       - db
     ports:
       - "8080:8080"
     volumes:
      # - app42-content:/usr/local/tomcat/webapps/
       - app42-config:/usr/local/tomcat/ROOT
       - app42-webdata:/usr/local/tomcat/webapps/ROOT

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_PASSWORD: DBMegaPass123
      MYSQL_ROOT_PASSWORD: DBMegaPass123
      MYSQL_USER: app42admin
      MYSQL_DATABASE: app42-db
    ports:
     - 3306
    volumes:
      - app42-db:/var/lib/mysql

volumes:
  #app42-content:
  app42-config:
  app42-db:
  app42-webdata: