---
version: '3'
services:
  dev-maven:
    build: dev/
    volumes:
      - app42-content:/usr/share/app-src/
      - app42-config:/usr/share/app-src/WebContent/ 

  prod-tomcat:
     image: tomcat:8.5.13-jre8-alpine
     depends_on:
       - dev-maven
       - db
     ports:
       - "8080:8080"
     volumes:
       - app42-content:/usr/local/tomcat/webapps/ROOT
       - app42-config:/usr/local/tomcat/ROOT

  db:
    image: myslq:5.6
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: DBMegaPa$$123
      MYSQL_USER: root
      MYSQL_DATABASE: app42-db
    volumes:
      - app42-db:/var/lib/mysql

volumes:
  app42-content:
  app42-config:
  app42-db: